apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
      - faketure-aks-ingress.centralus.cloudapp.azure.com
      secretName: tls-secret
  rules:
  - host: faketure-aks-ingress.centralus.cloudapp.azure.com
    http:
      paths:
      - path: /product/
        backend:
          serviceName: product-product
          servicePort: 8080
      - path: /cart/
        backend:
          serviceName: cart-cart
          servicePort: 8080
